# Тема “Вычисления с помощью Numpy”

## Задание 1

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 3, 1],
              [6, 8, 11, 10, 7]])
a = a.T

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = a.mean(axis=0)

In [5]:
mean_a

array([2. , 8.4])

## Задание 2

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

In [7]:
a_centered_sp = a_centered[:,0].dot(a_centered[:,1])
a_centered_sp

8.0

In [8]:
a_centered_sp /= a_centered.shape[0] - 1
a_centered_sp

2.0

## Задание 4

In [9]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

# Тема “Работа с данными в Pandas”

## Задание 1

In [10]:
import pandas as pd

In [11]:
author_id = [1, 2, 3]
author_name = ['Тургенев', 'Чехов', 'Островский']

In [12]:
authors_dict = {
    'author_id': author_id,
    'author_name': author_name
}
authors = pd.DataFrame(authors_dict)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [13]:
book_dict = {
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
}
book = pd.DataFrame(book_dict)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Задание 2

In [14]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 3

In [15]:
top_5 = authors_price.sort_values(by = 'price', ascending = False)[:5]
top_5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [16]:
top_5_1 = authors_price.nlargest(5, 'price')
top_5_1

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Задание 4

In [43]:
spam =  authors_price.groupby('author_name')
authors_stat = pd.DataFrame()
authors_stat['max_price'] = spam.agg({'price': 'max'})
authors_stat['min_price'] = spam.agg({'price': 'min'})
authors_stat['mean_price'] = spam.agg({'price': 'mean'})
authors_stat

max_price  min_price  mean_price
author_name                                  
Островский         370        290  330.000000
Тургенев           450        300  366.666667
Чехов              500        450  475.000000

## Задание 5

In [45]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [50]:
book_info = pd.pivot_table(authors_price,
               values = 'price',
               index = 'author_name',
               columns = 'cover',
              aggfunc = 'sum',
              fill_value = 0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [56]:
book_info.to_pickle("book_info.pkl")

In [57]:
book_info2 = pd.read_pickle("book_info.pkl")

In [63]:
book_info == book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True